name: ddgs
description: DDGS | Dux Distributed Global Search. A metasearch library that aggregates results from diverse web search services.
version: 0.1.0
repository: https://github.com/Kamran1819G/ddgs

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  html: ^0.15.4
  xml: ^6.3.0
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
